---
- name: Install Postgres repository rpm from a remote repo
  become: true
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL 10
  become: true
  yum:
    name:
      - postgresql10-devel
      - postgresql10-server
      - postgresql10-contrib
      - postgresql10-libs
      - postgresql10
      - python3-psycopg2
      - libpq5
      - libpq5-devel
    state: present

- name: Find out if PostgreSQL is initialized
  become: true
  ansible.builtin.stat:
    path: /var/lib/pgsql/10/data/pg_hba.conf
  register: postgres_data

- name: Initialize database
  become: true
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  when: not postgres_data.stat.exists

- name: Start Postgres
  become: true
  command: systemctl start postgresql-10.service

- name: Enable Postgres
  become: true
  command: systemctl enable postgresql-10.service

- become: true
  become_user: postgres
  block:
    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Create PostgreSQL users
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        db: "{{ database_name }}"
        encrypted: yes
        priv: ALL

    - name: Add PostgreSQL extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "{{database_name}}"
      with_items:
        - plpgsql
        - unaccent
        - pg_trgm

- name: Allow local login
  become: true
  lineinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    line: 'host    all             all             127.0.0.1/32            md5'
    regexp: '^host( )*all( )*all( )*127\.0\.0\.1\/32( )*ident*'
    state: present

- name: Allow local login
  become: true
  lineinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    line: 'host    all             all             ::1/128            md5'
    regexp: '^host( )*all( )*all( )*::1/128 ( )*ident*'
    state: present

- name: Re-start the service
  become: true
  command: systemctl restart postgresql-10.service
