---
- name: Remove pre-installed PostgreSQL versions
  become: true
  package:
    name:
      - postgresql*9.0*
      - postgresql*9.1*
      - postgresql*9.2*
      - postgresql*9.3*
    state: absent

- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2

- name: Start Postgres
  become: true
  command: systemctl start postgresql

- become: true
  become_user: postgres
  block:
    - name: Get PostgreSQL version
      shell: "dpkg -l | grep postgres"
      register: psql_version
    - name: Print PostgreSQL version
      debug:
        msg: "{{ psql_version.stdout }}"
    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Create PostgreSQL users
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        db: "{{ database_name }}"
        encrypted: yes
        priv: ALL

    - name: Add PostgreSQL extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "{{database_name}}"
      with_items:
        - plpgsql
        - unaccent
        - pg_trgm
