---
- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Add default virtual host
  template:
    src: "{{ playbook_dir }}/roles/nginx/templates/consul_vhost.j2"
    dest: /etc/nginx/conf.d/consul.conf
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
