- name: Check if locale '{{ locale }}' is set up
  shell: localectl status | grep -i {{ locale }}
  register: found_locale
  changed_when: no
  failed_when: no

- name: Set up locale to '{{ locale }}' and language to '{{ locale }}'
  become: true
  shell: localectl set-locale LANG={{ locale }} LANGUAGE={{ locale }}
  when: found_locale.rc != 0

- name: Check if timezone '{{ timezone }}' is set up
  shell: timedatectl status | grep -i {{ timezone }}
  register: found_timezone
  changed_when: no
  failed_when: no

- name: Configure timezone to '{{ timezone }}'
  become: true
  shell: ln -sf /usr/share/zoneinfo/{{ timezone }} /etc/localtime
  when: found_timezone.rc != 0
