---
- name: gather facts
  setup:

- name: Print environment settings
  debug:
    msg: "Setting up {{ env }} environment"

- name: Update and upgrade yum packages (this may take a few minutes)
  become: yes
  yum:
    name: "*"
    state: latest
    update_only: yes

#- include: hostname.yml
- include: tools.yml
