---
- name: Add Nodesource repositories for Node.js 10.x (CentOS 7+).
  become: true
  yum:
    name: http://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: present

- name: Install tools
  become: true
  yum:
    name:
      - audit
      - policycoreutils-devel
      - python3-devel
      - tmux
      - vim
      - htop
      - git
      - wget
      - libxml2
      - curl
      - nodejs
      - ImageMagick
      - setools
    state: latest
