---
- name: Create pids and sockets folders
  file:
    path: "{{ shared_dir }}/tmp/{{ item }}"
    state: directory
  with_items:
    - "pids"
    - "sockets"

- name: Create systemd folder
  file:
    path: "{{ home_dir }}/.config/systemd/user"
    state: directory

- name: Copy Puma service file to the systemd folder
  template:
    src: "{{ playbook_dir }}/roles/puma/templates/puma.service"
    dest: "{{ home_dir }}/.config/systemd/user/puma.service"

- name: Start puma
  systemd:
    name: "{{ puma_service_unit_name }}"
    enabled: true
    state: started
    scope: user

- name: Make sure Nginx has write access to the puma socket
  shell: "chmod o+w tmp/sockets/*"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash
