---
- name: Creates shared initializers folder
  file:
    path: "{{ shared_dir }}/config/initializers"
    state: directory

- name: Copy delayed jobs configuration to shared folder
  command: "cp {{ release_dir }}/config/initializers/delayed_job_config.rb {{ shared_dir }}/config/initializers/delayed_job_config.rb"
