name: ubuntu
on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        rails_env: [staging, production]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
        if: ${{ matrix.os != 'ubuntu-20.04' }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
        if: ${{ matrix.os == 'ubuntu-20.04' }}
      - name: Update system packages
        run: sudo apt-get update -y
      - name: Install OpenSSH
        run: sudo apt-get install -y openssh-server
      - name: Install Ansible
        run: pip3 install ansible
      - name: Create hosts file
        run: echo "localhost ansible_connection=local ansible_user=root" > hosts
      - name: Generate dummy SSH key
        run: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - name: Run CONSUL installer
        run: ansible-playbook consul.yml -i hosts --extra-vars "env=${{ matrix.rails_env }} domain=localhost"
      - name: Check permissions
        run: ls -l /home/deploy/consul/shared/tmp/sockets/ > /home/deploy/consul/shared/log/permit.log
      - name: Check permission details
        run: getfacl /home/deploy/consul/shared/tmp/sockets/* > details.log
      - name: Check Selinux
        run: dpkg -l | grep selinux > /home/deploy/consul/shared/log/selinux.log
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /home/deploy/consul/shared/log
